### ISSUE TITLE
Elasticsearch registry implementation does not split data into fields

### ISSUE THREAD

**Issue by lapistano** [liip/LiipDrupalRegistryModule#13]
The Elasticsearch implemetation of the registry kind of requires a serialized string which will be written in just one field of an index. 
This does not seem to be the best way to store data in elasticsearch, neither the most useful. 
I propose to rewrite the implementation to store received data how it is the best way for elasticsearch to be able to use all the benefits you can get from it.

**Comment by pjezek** [comment]
Since latest refactoring we support now Decorators for the Elasticsearch registry. The NoOpDecorator does not do any normalisation or denormalization. With it fields where returned as obtained from es. The NormalizeDecorator requires the data to be stored as array or object and serializes the data into a single field.
